### ISSUE TITLE
Segfault when using predict_vis to apply DIE gains

### ISSUE THREAD

**Issue by landmanbester** [ska-sa/codex-africanus#102]
@sjperkins will you please have a look at what I am trying [here](https://github.com/landmanbester/codex-africanus/blob/calibration_utils/africanus/calibration/examples/phase_only_scalar_calibration.py). Up until l77 I am just loading in data and building the DIE jones matrix in gains_true. When I try to apply them with predict_vis I am getting 

(codex-africanus) landman-X3 :: africanus/calibration/examples ‹calibration_utils*› » ./phase_only_scalar_calibration.py /home/landman/Projects/Data/MS_dir/mfs_sky.MS_p0
Successful readonly open of default-locked table /home/landman/Projects/Data/MS_dir/mfs_sky.MS_p0: 26 columns, 2808 rows
Successful readonly open of default-locked table /home/landman/Projects/Data/MS_dir/mfs_sky.MS_p0/SPECTRAL_WINDOW: 14 columns, 1 rows
[0 1 2 3 4 5 6 7]
[1]    6913 segmentation fault  ./phase_only_scalar_calibration.py   

I assume time_index are the indices of the unique time stamps. Is that correct? Can you see anything obviously wrong with how I am using predict_vis?

This branch has the latest version of master merged in and numba is at the latest version.

**Comment by sjperkins** [comment]
From a quick look, I think you want to be passing model via base_vis rather than source_coh. It also probably needs a reshape on the correlation dimension before it goes in.

predict_vis probably needs more internal checks here, it sound fail earlier on the shapes and dimensions.

Incidentally, time_index can be derived from np.unique(TIME, return_inverse=True) but I think that's only mentioned in the dask docs

**Comment by landmanbester** [comment]
Awesome, thanks. Works if I get

time_index = np.unique(time, return_inverse=True)[1]

(Note the [1])
